---
ID: "c7d26ec9-43b3-42a8-b418-59d774767a1f"
Parent: "6e963693-a285-4aa6-9fe0-860782843627"
Template: "6e963693-a285-4aa6-9fe0-860782843627"
Path: /sitecore/templates/Feature/EspireDemo/Social Sharing/Component/Social Media Feeds/Social Media Feeds/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230817T100848Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\manoj.chopkar@espire.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\manoj.chopkar@espire.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "16be8acf-c909-418c-ae35-bfe682f94a49"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\manoj.chopkar@espire.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230817T100848Z
