---
ID: "10745b24-e14e-47cf-b6ae-15d26e1891a9"
Parent: "0fb17ab6-d336-4840-9a73-eb7fe7352893"
Template: "0fb17ab6-d336-4840-9a73-eb7fe7352893"
Path: /sitecore/templates/Feature/EspireDemo/PageContent/Components/Plain HTML Reusable/Plain HTML Reusable Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {FCE0C0A1-0453-43DE-A82F-9655B1AA06C6}
    {0FB17AB6-D336-4840-9A73-EB7FE7352893}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230717T092817Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\raman.gupta@espire.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\raman.gupta@espire.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "60cff66b-4a19-440d-a4d7-58a95496e4a5"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\raman.gupta@espire.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230717T092901Z
