---
ID: "093770e8-5232-4716-9ee8-2aca5b9a81cd"
Parent: "b815b680-a50c-43f3-9da4-d2631cca7a02"
Template: "b815b680-a50c-43f3-9da4-d2631cca7a02"
Path: /sitecore/templates/Feature/EspireDemo/Social Sharing/Component/Social Media Share/Social Media Item Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{91826226-4F91-4791-9B14-E201B1D9CB2C}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230821T063500Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\manoj.chopkar@espire.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\manoj.chopkar@espire.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "232b2203-0b02-4745-ab24-7d8c28d55a69"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\manoj.chopkar@espire.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230821T064011Z
