---
ID: "af807e33-5fca-4aef-bcb5-a24c6598d210"
Parent: "f342a33a-a47b-4c86-9756-a47152803bb6"
Template: "f342a33a-a47b-4c86-9756-a47152803bb6"
Path: /sitecore/templates/Feature/EspireDemo/Listing/Rendering Parameter/Listing Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230807T161403Z
    - ID: "3c45c1b3-3dd0-47ae-a611-3d33937198a9"
      Hint: Display Count
      Value: 5
    - ID: "3c4a621d-75e5-4f2a-85c0-cf29481008be"
      Hint: Show More
      Value: 1
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\manoj.chopkar@espire.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\manoj.chopkar@espire.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "4f80c94d-d24a-4764-8353-2dff92e5aa16"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\manoj.chopkar@espire.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230808T102300Z
