---
ID: "9800d3e0-4021-4746-8e21-44fe91a9c210"
Parent: "444aebf2-8f50-4185-86c1-d88c9d2cb3d7"
Template: "444aebf2-8f50-4185-86c1-d88c9d2cb3d7"
Path: /sitecore/templates/Feature/EspireDemo/PageContent/Rendering Parameters/RichText Reusable/__Standard Values
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: applications/16x16/notebook.png
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230717T084842Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\raman.gupta@espire.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\raman.gupta@espire.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a981e42a-fefb-45a4-8573-dc2287d518df"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\raman.gupta@espire.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230717T085003Z
