---
ID: "14b72195-f72e-4369-95ed-beb341a73dcc"
Parent: "174ec1c6-32d3-4a1d-9230-d1160d0c62a6"
Template: "174ec1c6-32d3-4a1d-9230-d1160d0c62a6"
Path: /sitecore/templates/Feature/EspireDemo/PageContent/Rendering Parameters/Plain HTML Resuable/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230717T092922Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\raman.gupta@espire.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\raman.gupta@espire.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "75d650d6-fb54-4f9a-b07c-5536ce089a05"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\raman.gupta@espire.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230717T092922Z
