---
ID: "efc8c846-cba0-4bd5-9b35-22dedceb1f06"
Parent: "caac3401-9b24-44ce-a0eb-9260024ed02c"
Template: "caac3401-9b24-44ce-a0eb-9260024ed02c"
Path: /sitecore/templates/Feature/EspireDemo/PageContent/Components/MapComponent/MapComponentFolder/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231103T071125Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\manoj.chopkar@espire.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\manoj.chopkar@espire.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e983e066-e8ec-4945-a6da-87aef20d4f14"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\manoj.chopkar@espire.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231103T071125Z
