---
ID: "24fc4f93-4757-4cd9-8528-f3d5702937ae"
Parent: "8ca06d6a-b353-44e8-bc31-b528c7306971"
Template: "8ca06d6a-b353-44e8-bc31-b528c7306971"
Path: /sitecore/templates/System/Layout/Rendering Parameters/Standard Rendering Parameters/__Standard Values
SharedFields:
- ID: "3094d236-5985-4c4f-ae6a-e30740885532"
  Hint: Caching
  Value: 0|0|0|0|0|0|0|0
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20090420T134752
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a4ec821f-cfe6-441d-8728-04b8f1a39008"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210622T112539Z
