---
ID: "2edbec30-d3f6-4bc1-983c-51f349942479"
Parent: "0c9eb3f7-47d1-4cc3-b8ab-9011cb5a473f"
Template: "0c9eb3f7-47d1-4cc3-b8ab-9011cb5a473f"
Path: /sitecore/templates/Feature/EspireDemo/PageContent/Rendering Parameters/Banner/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230713T144500Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\raman.gupta@espire.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\raman.gupta@espire.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "340f528b-ba8b-4ef6-baef-3cb6c02960c7"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\raman.gupta@espire.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230713T144626Z
