---
ID: "f2834eb1-b16b-4c1b-b6c4-291a3faadc24"
Parent: "f20a5ade-599c-4d89-8f60-c47a40753697"
Template: "f20a5ade-599c-4d89-8f60-c47a40753697"
Path: /sitecore/templates/Project/EspireDemo/Details/Article Details/__Standard Values
SharedFields:
- ID: "4a749557-242b-4372-8a20-b2db9d406301"
  Hint: __AutoThumbnails
  Value: 
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{96E5F4BA-A2CF-4A4C-A4E7-64DA88226362}" />
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230928T065409Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\manoj.chopkar@espire.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\manoj.chopkar@espire.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "dd53254c-57f8-4607-ae23-33105c4dbbbf"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\manoj.chopkar@espire.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230928T095557Z
