---
ID: "03f76fc7-16e9-400f-bece-2a778e182ffd"
Parent: "8cd05019-a4d8-4157-86bd-46096028c908"
Template: "8cd05019-a4d8-4157-86bd-46096028c908"
Path: /sitecore/templates/Feature/EspireDemo/PageContent/Components/Head Script/Head Script Folder/__Standard Values
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: /~/icon/applicationsv2/32x32/folder_add.png
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {8CD05019-A4D8-4157-86BD-46096028C908}
    {66FA9BE4-D704-45A2-8420-4EB3ECE556B6}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231003T121929Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\manoj.chopkar@espire.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\manoj.chopkar@espire.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ac1e98b0-4036-4012-880e-ae39b9ca4f7d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\manoj.chopkar@espire.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231003T122139Z
