---
ID: "5cbf867f-df7a-4d51-b30a-16c94f2d28e3"
Parent: "204d8962-1bd1-4327-99eb-e2b9cc01d32f"
Template: "204d8962-1bd1-4327-99eb-e2b9cc01d32f"
Path: /sitecore/templates/Feature/EspireDemo/Composites/Components/Tabs/Tabs Root/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{DF44C08A-73B1-4074-99CD-C6783E33C8BC}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230719T071959Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\b6hiKrOdCH
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\b6hiKrOdCH
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "37082459-51fe-40de-9158-9638ed47327f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\b6hiKrOdCH
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230719T072303Z
