---
ID: "ac491675-b7f9-4b22-8e0e-2471e58566ba"
Parent: "695d478b-660f-4d61-a682-3fbdc9e56115"
Template: "695d478b-660f-4d61-a682-3fbdc9e56115"
Path: /sitecore/templates/Feature/EspireDemo/Composites/Components/Carousel/Carousel Data/__Standard Values
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: /~/icon/applications/32x32/folder_add.png
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {695D478B-660F-4D61-A682-3FBDC9E56115}
    {8B230685-2244-4590-A0C4-7FD896B9C8C0}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230725T042527Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\b6hiKrOdCH
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\b6hiKrOdCH
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8eb5e773-70df-42a9-ae7d-79c2dd00d676"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\b6hiKrOdCH
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230725T042701Z
