---
ID: "542626f8-434c-4b2f-86a2-22d2f4a55b39"
Parent: "2755ac13-96b9-4e09-a2a0-c2ed80f89ded"
Template: "2755ac13-96b9-4e09-a2a0-c2ed80f89ded"
Path: /sitecore/templates/Feature/EspireDemo/PageContent/Rendering Parameters/Language Selector/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230713T152103Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\raman.gupta@espire.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\raman.gupta@espire.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "24011691-4ff9-40e3-978d-bfdf08f03b31"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\raman.gupta@espire.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230713T152120Z
